import { type Locale } from "./i18n";

export interface CityConfig {
  id: string;
  name: Record<Locale, string>;
  hasPlaces: boolean;
}

export const CITIES: CityConfig[] = [
  {
    id: "kyiv",
    name: {
      en: "Kyiv",
      uk: "Київ",
      ru: "Киев",
      de: "Kiew",
      pl: "Kijów",
      fr: "Kyiv",
      it: "Kyiv",
      es: "Kyiv",
    },
    hasPlaces: true,
  },
  {
    id: "warsaw",
    name: {
      en: "Warsaw",
      uk: "Варшава",
      ru: "Варшава",
      de: "Warschau",
      pl: "Warszawa",
      fr: "Varsovie",
      it: "Varsavia",
      es: "Varsovia",
    },
    hasPlaces: true,
  },
  {
    id: "lviv",
    name: {
      en: "Lviv",
      uk: "Львів",
      ru: "Львов",
      de: "Lemberg",
      pl: "Lwów",
      fr: "Lviv",
      it: "Leopoli",
      es: "Leópolis",
    },
    hasPlaces: false,
  },
  {
    id: "krakow",
    name: {
      en: "Kraków",
      uk: "Краків",
      ru: "Краков",
      de: "Krakau",
      pl: "Kraków",
      fr: "Cracovie",
      it: "Cracovia",
      es: "Cracovia",
    },
    hasPlaces: false,
  },
  {
    id: "wroclaw",
    name: {
      en: "Wrocław",
      uk: "Вроцлав",
      ru: "Вроцлав",
      de: "Breslau",
      pl: "Wrocław",
      fr: "Wrocław",
      it: "Breslavia",
      es: "Breslavia",
    },
    hasPlaces: false,
  },
  {
    id: "odesa",
    name: {
      en: "Odesa",
      uk: "Одеса",
      ru: "Одесса",
      de: "Odessa",
      pl: "Odessa",
      fr: "Odessa",
      it: "Odessa",
      es: "Odesa",
    },
    hasPlaces: false,
  },
  {
    id: "dnipro",
    name: {
      en: "Dnipro",
      uk: "Дніпро",
      ru: "Днепр",
      de: "Dnipro",
      pl: "Dniepr",
      fr: "Dnipro",
      it: "Dnipro",
      es: "Dnipro",
    },
    hasPlaces: false,
  },
  {
    id: "kharkiv",
    name: {
      en: "Kharkiv",
      uk: "Харків",
      ru: "Харьков",
      de: "Charkiw",
      pl: "Charków",
      fr: "Kharkiv",
      it: "Charkiv",
      es: "Járkov",
    },
    hasPlaces: false,
  },
  {
    id: "london",
    name: {
      en: "London",
      uk: "Лондон",
      ru: "Лондон",
      de: "London",
      pl: "Londyn",
      fr: "Londres",
      it: "Londra",
      es: "Londres",
    },
    hasPlaces: false,
  },
  {
    id: "paris",
    name: {
      en: "Paris",
      uk: "Париж",
      ru: "Париж",
      de: "Paris",
      pl: "Paryż",
      fr: "Paris",
      it: "Parigi",
      es: "París",
    },
    hasPlaces: false,
  },
  {
    id: "berlin",
    name: {
      en: "Berlin",
      uk: "Берлін",
      ru: "Берлин",
      de: "Berlin",
      pl: "Berlin",
      fr: "Berlin",
      it: "Berlino",
      es: "Berlín",
    },
    hasPlaces: false,
  },
  {
    id: "prague",
    name: {
      en: "Prague",
      uk: "Прага",
      ru: "Прага",
      de: "Prag",
      pl: "Praga",
      fr: "Prague",
      it: "Praga",
      es: "Praga",
    },
    hasPlaces: false,
  },
  {
    id: "vienna",
    name: {
      en: "Vienna",
      uk: "Відень",
      ru: "Вена",
      de: "Wien",
      pl: "Wiedeń",
      fr: "Vienne",
      it: "Vienna",
      es: "Viena",
    },
    hasPlaces: false,
  },
  {
    id: "newyork",
    name: {
      en: "New York",
      uk: "Нью-Йорк",
      ru: "Нью-Йорк",
      de: "New York",
      pl: "Nowy Jork",
      fr: "New York",
      it: "New York",
      es: "Nueva York",
    },
    hasPlaces: false,
  },
  {
    id: "tokyo",
    name: {
      en: "Tokyo",
      uk: "Токіо",
      ru: "Токио",
      de: "Tokio",
      pl: "Tokio",
      fr: "Tokyo",
      it: "Tokyo",
      es: "Tokio",
    },
    hasPlaces: false,
  },
  {
    id: "rome",
    name: {
      en: "Rome",
      uk: "Рим",
      ru: "Рим",
      de: "Rom",
      pl: "Rzym",
      fr: "Rome",
      it: "Roma",
      es: "Roma",
    },
    hasPlaces: false,
  },
  {
    id: "barcelona",
    name: {
      en: "Barcelona",
      uk: "Барселона",
      ru: "Барселона",
      de: "Barcelona",
      pl: "Barcelona",
      fr: "Barcelone",
      it: "Barcellona",
      es: "Barcelona",
    },
    hasPlaces: false,
  },
  {
    id: "amsterdam",
    name: {
      en: "Amsterdam",
      uk: "Амстердам",
      ru: "Амстердам",
      de: "Amsterdam",
      pl: "Amsterdam",
      fr: "Amsterdam",
      it: "Amsterdam",
      es: "Ámsterdam",
    },
    hasPlaces: false,
  },
  {
    id: "losangeles",
    name: {
      en: "Los Angeles",
      uk: "Лос-Анджелес",
      ru: "Лос-Анджелес",
      de: "Los Angeles",
      pl: "Los Angeles",
      fr: "Los Angeles",
      it: "Los Angeles",
      es: "Los Ángeles",
    },
    hasPlaces: false,
  },
];
