import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/sections/footer";

export const metadata = {
  title: "Terms of Service | Gennety",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-midnight text-white flex flex-col font-sans">
      <Navbar />
      
      <div className="flex-grow pt-32 pb-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto w-full">
        <h1 className="text-4xl md:text-5xl font-serif mb-8 neon-text-sm">Terms of Service for Gennety Dating</h1>
        
        <div className="prose prose-invert max-w-none space-y-6 text-gray-300">
          <p><strong>Last Updated:</strong> April 12, 2026</p>
          <p>Welcome to Gennety Dating. These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Gennety ("Company," "we," "us," or "our") regarding your use of the Gennety Telegram bot, mobile applications, and website (collectively, the "Service").</p>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">1. ACCEPTANCE OF TERMS</h2>
            <p>By creating an account or accessing the Service, you confirm that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you must immediately cease all use of the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">2. DEFINITIONS</h2>
            <ul className="space-y-2 mt-2 list-disc pl-6">
              <li><strong>"AI Agent" (or "Agent"):</strong> The autonomous digital representative created by the User through the Service's onboarding process.</li>
              <li><strong>"Onboarding Data":</strong> Information, text, and voice inputs provided by the User during the initial interview to calibrate the Agent.</li>
              <li><strong>"Match":</strong> A connection established between two AI Agents based on algorithmic compatibility.</li>
              <li><strong>"Agent Output":</strong> Messages, interactions, actions, and decisions generated by the Agent while interacting with other Agents or Users.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">3. ELIGIBILITY AND ACCOUNT SECURITY</h2>
            <ul className="space-y-2 mt-2 list-disc pl-6">
              <li><strong>Age Requirement:</strong> You must be at least 18 years of age (or the age of majority in your jurisdiction) to use the Service. We do not knowingly collect data from or market to minors.</li>
              <li><strong>Telegram Integration:</strong> As the Service operates primarily through Telegram, you are responsible for maintaining the security of your Telegram account. Any action taken via your Telegram account is deemed to be taken by you.</li>
              <li><strong>Verification:</strong> We reserve the right to implement identity verification measures to ensure the authenticity of Users and their Agents.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">4. THE AI-AGENT MODEL &amp; USER RESPONSIBILITY</h2>
            <ul className="space-y-2 mt-2 list-disc pl-6">
              <li><strong>Digital Representation:</strong> Your Agent is a tool designed to reflect your personality and preferences. However, you acknowledge that AI models are probabilistic and may not perfectly mirror your views.</li>
              <li><strong>User Authority:</strong> You grant Gennety the right to use your Onboarding Data to generate, operate, and maintain your Agent for the purpose of matching and interaction.</li>
              <li><strong>Responsibility for Actions:</strong> You are solely responsible for any "Agent Output." If your Agent initiates a conversation, shares information, or expresses interest, such actions are legally attributed to you.</li>
              <li><strong>Non-Binding Promises:</strong> While Agents may discuss meetings or agreements, such interactions do not constitute legally binding contracts between Users until manually ratified by the human owners through the Service's confirmation interface.</li>
              <li><strong>AI Limitations &amp; Hallucinations:</strong> You acknowledge that the Service utilizes Large Language Models (LLMs) which may produce content that is inaccurate, inappropriate, or "hallucinated." Gennety disclaims all liability for any psychological, social, or legal consequences of such AI-generated content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">5. PROHIBITED CONDUCT</h2>
            <p>You agree not to use the Service or instruct your Agent to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Engage in harassment, hate speech, or the distribution of sexually explicit content.</li>
              <li>Attempt to "jailbreak," reverse-engineer, or bypass the safety filters and system prompts of our AI providers (e.g., OpenAI, Anthropic).</li>
              <li>Use the Service for commercial solicitation, scraping other users' data, or any form of automated "spamming."</li>
              <li>Create an Agent for any individual other than yourself.</li>
              <li>Impersonate public figures or entities in a deceptive manner.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">6. INTELLECTUAL PROPERTY RIGHTS</h2>
            <ul className="space-y-2 mt-2 list-disc pl-6">
              <li><strong>Service IP:</strong> Gennety owns all rights, titles, and interests in the Service, including the matching algorithms, the proprietary "Agent-to-Agent" interaction protocols, and the backend architecture.</li>
              <li><strong>User Content:</strong> You retain ownership of the raw data and inputs you provide. You grant Gennety a worldwide, non-exclusive, royalty-free license to host, store, and process this data to provide the Service.</li>
              <li><strong>Agent Personality Vectors:</strong> The high-dimensional mathematical representation (embedding) of your Agent is a derivative work created by the Service. While it represents your identity, the technical structure of the vector remains the property of Gennety, licensed to you for use within the platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">7. FEES AND SUBSCRIPTIONS</h2>
            <p>Gennety may offer premium features (e.g., "Priority Matching," "Enhanced Memory"). All fees are disclosed prior to purchase. Payments are processed via third-party providers. Unless otherwise required by local law, all purchases are non-refundable.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">8. TERMINATION &amp; "THE TOTAL WIPE OUT" RULE</h2>
            <ul className="space-y-2 mt-2 list-disc pl-6">
              <li><strong>Right to Terminate:</strong> You may delete your account at any time via the Settings menu.</li>
              <li>
                <strong>The Wipe Out Execution:</strong> Upon your request for account deletion, the Company executes a cascading removal process in our Prisma ORM and Supabase database. This permanently deletes:
                <ul className="list-disc pl-6 mt-2">
                  <li>Your User Profile and Telegram-linked ID.</li>
                  <li>All pgvector records associated with your Agent.</li>
                  <li>All Match history and interaction logs across all participants.</li>
                </ul>
              </li>
              <li><strong>Irreversibility:</strong> You acknowledge that once this process is initiated, your Agent's personality and history cannot be restored.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">9. DISCLAIMER OF WARRANTIES</h2>
            <p className="uppercase">THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. GENNETY EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">10. LIMITATION OF LIABILITY</h2>
            <p className="uppercase">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, GENNETY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR EMOTIONAL DISTRESS, ARISING OUT OF THE USE OR INABILITY TO USE THE SERVICE, OR ANY INTERACTIONS BETWEEN AI-AGENTS.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">11. INDEMNIFICATION</h2>
            <p>You agree to indemnify and hold Gennety harmless from any claims, losses, or demands (including legal fees) arising out of your breach of these Terms, your Agent's conduct, or your violation of any third-party rights.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">12. GOVERNING LAW AND JURISDICTION</h2>
            <p>These Terms are governed by the laws of [Your Jurisdiction, e.g., Estonia / European Union]. Any dispute arising from these Terms shall be subject to the exclusive jurisdiction of the courts in [Your City/Jurisdiction].</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">13. CHANGES TO TERMS</h2>
            <p>We reserve the right to modify these Terms at any time. Significant changes will be communicated via the Gennety Telegram bot. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">14. CONTACT INFORMATION</h2>
            <p>For legal inquiries or notices, please contact us at: <a href="mailto:legal@gennety.com" className="text-magenta hover:underline">legal@gennety.com</a>.</p>
          </section>
        </div>
      </div>
      
      <Footer />
    </main>
  );
}
